CREATE DATABASE IF NOT EXISTS yun_tan_fang DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE yun_tan_fang;

-- 待替换为正式 SQL：当前为项目框架阶段的最小结构骨架。
CREATE TABLE IF NOT EXISTS t_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL,
  password_hash VARCHAR(128) NOT NULL DEFAULT '',
  account_type VARCHAR(32) NOT NULL DEFAULT 'consumer',
  mobile VARCHAR(32),
  wechat_id VARCHAR(64),
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_role (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  role_code VARCHAR(64) NOT NULL UNIQUE,
  role_name VARCHAR(64) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_user_role (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_vendor (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  vendor_name VARCHAR(128) NOT NULL,
  story TEXT,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_qualification (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  vendor_id BIGINT NOT NULL,
  qualification_type VARCHAR(64) NOT NULL,
  media_url VARCHAR(512),
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_vendor_audit (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  vendor_id BIGINT NOT NULL,
  audit_status VARCHAR(32) NOT NULL,
  audit_opinion VARCHAR(512),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_special_identity (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  vendor_id BIGINT NOT NULL,
  identity_type VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_area (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  area_name VARCHAR(128) NOT NULL,
  fence_geojson JSON,
  status VARCHAR(32) NOT NULL DEFAULT 'enabled',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_admin (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL,
  password_hash VARCHAR(128) NOT NULL DEFAULT '',
  role_code VARCHAR(64) NOT NULL DEFAULT 'admin',
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_supervisor (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL,
  area_id BIGINT,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_stall (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  vendor_id BIGINT,
  area_id BIGINT,
  stall_name VARCHAR(128) NOT NULL,
  business_status VARCHAR(32) NOT NULL DEFAULT 'closed',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_stall_reservation (id BIGINT PRIMARY KEY AUTO_INCREMENT, vendor_id BIGINT, stall_id BIGINT, status VARCHAR(32) NOT NULL DEFAULT 'pending', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS t_stall_schedule (id BIGINT PRIMARY KEY AUTO_INCREMENT, stall_id BIGINT, schedule_date DATE, status VARCHAR(32) NOT NULL DEFAULT 'published', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS t_stall_checkin (id BIGINT PRIMARY KEY AUTO_INCREMENT, stall_id BIGINT, latitude DECIMAL(10,7), longitude DECIMAL(10,7), status VARCHAR(32) NOT NULL DEFAULT 'checked', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS t_stall_status_log (id BIGINT PRIMARY KEY AUTO_INCREMENT, stall_id BIGINT, status VARCHAR(32) NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS t_product_category (id BIGINT PRIMARY KEY AUTO_INCREMENT, category_name VARCHAR(128) NOT NULL, status VARCHAR(32) NOT NULL DEFAULT 'enabled', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS t_product (id BIGINT PRIMARY KEY AUTO_INCREMENT, vendor_id BIGINT, category_id BIGINT, product_name VARCHAR(128) NOT NULL, price DECIMAL(10,2), status VARCHAR(32) NOT NULL DEFAULT 'draft', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS t_product_media (id BIGINT PRIMARY KEY AUTO_INCREMENT, product_id BIGINT, media_url VARCHAR(512), media_type VARCHAR(32), status VARCHAR(32) NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS t_content_audit (id BIGINT PRIMARY KEY AUTO_INCREMENT, biz_type VARCHAR(64), biz_id BIGINT, status VARCHAR(32) NOT NULL DEFAULT 'pending', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS t_order (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT, vendor_id BIGINT, order_status VARCHAR(32) NOT NULL DEFAULT 'created', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS t_order_item (id BIGINT PRIMARY KEY AUTO_INCREMENT, order_id BIGINT, product_id BIGINT, quantity INT NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS t_payment (id BIGINT PRIMARY KEY AUTO_INCREMENT, order_id BIGINT, payment_status VARCHAR(32) NOT NULL DEFAULT 'unpaid', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS t_settlement (id BIGINT PRIMARY KEY AUTO_INCREMENT, vendor_id BIGINT, status VARCHAR(32) NOT NULL DEFAULT 'pending', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS t_order_status_log (id BIGINT PRIMARY KEY AUTO_INCREMENT, order_id BIGINT, order_status VARCHAR(32) NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS t_review (id BIGINT PRIMARY KEY AUTO_INCREMENT, order_id BIGINT, user_id BIGINT, rating INT, status VARCHAR(32) NOT NULL DEFAULT 'published', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS t_review_media (id BIGINT PRIMARY KEY AUTO_INCREMENT, review_id BIGINT, media_url VARCHAR(512), media_type VARCHAR(32), created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS t_follow (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT, vendor_id BIGINT, status VARCHAR(32) NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS t_favorite (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT, biz_type VARCHAR(64), biz_id BIGINT, status VARCHAR(32) NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS t_subscribe (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT, vendor_id BIGINT, status VARCHAR(32) NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS t_complaint (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT, vendor_id BIGINT, description TEXT, status VARCHAR(32) NOT NULL DEFAULT 'submitted', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS t_complaint_media (id BIGINT PRIMARY KEY AUTO_INCREMENT, complaint_id BIGINT, media_url VARCHAR(512), media_type VARCHAR(32), created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS t_supervision_record (id BIGINT PRIMARY KEY AUTO_INCREMENT, complaint_id BIGINT, supervisor_id BIGINT, status VARCHAR(32) NOT NULL DEFAULT 'processed', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS t_violation_record (id BIGINT PRIMARY KEY AUTO_INCREMENT, vendor_id BIGINT, violation_type VARCHAR(64), status VARCHAR(32) NOT NULL DEFAULT 'recorded', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS t_timeout_alert (id BIGINT PRIMARY KEY AUTO_INCREMENT, biz_type VARCHAR(64), biz_id BIGINT, status VARCHAR(32) NOT NULL DEFAULT 'open', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS t_policy (id BIGINT PRIMARY KEY AUTO_INCREMENT, title VARCHAR(128) NOT NULL, content TEXT, status VARCHAR(32) NOT NULL DEFAULT 'draft', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS t_notice (id BIGINT PRIMARY KEY AUTO_INCREMENT, title VARCHAR(128) NOT NULL, content TEXT, status VARCHAR(32) NOT NULL DEFAULT 'draft', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS t_push_record (id BIGINT PRIMARY KEY AUTO_INCREMENT, notice_id BIGINT, status VARCHAR(32) NOT NULL DEFAULT 'pending', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);

INSERT IGNORE INTO t_role(role_code, role_name) VALUES
('consumer', '消费者'),
('vendor', '摊主'),
('admin', '管理人员'),
('auditor', '审核人员'),
('supervisor', '监管人员'),
('system_admin', '系统管理员');

SET @schema_name = DATABASE();
SET @sql = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE t_user ADD COLUMN password_hash VARCHAR(128) NOT NULL DEFAULT ''''', 'SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema_name AND TABLE_NAME = 't_user' AND COLUMN_NAME = 'password_hash');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE t_user ADD COLUMN account_type VARCHAR(32) NOT NULL DEFAULT ''consumer''', 'SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema_name AND TABLE_NAME = 't_user' AND COLUMN_NAME = 'account_type');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE t_admin ADD COLUMN password_hash VARCHAR(128) NOT NULL DEFAULT ''''', 'SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema_name AND TABLE_NAME = 't_admin' AND COLUMN_NAME = 'password_hash');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE t_admin ADD COLUMN role_code VARCHAR(64) NOT NULL DEFAULT ''admin''', 'SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema_name AND TABLE_NAME = 't_admin' AND COLUMN_NAME = 'role_code');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- 前端阶段测试账号。密码暂存明文，后续正式登录改为后端哈希校验。
DELETE FROM t_user_role WHERE user_id IN (SELECT id FROM t_user WHERE username IN ('test1', 'test2'));
DELETE FROM t_vendor WHERE user_id IN (SELECT id FROM t_user WHERE username = 'test2');
DELETE FROM t_user WHERE username IN ('test1', 'test2');
DELETE FROM t_admin WHERE username = 'test3';

INSERT INTO t_user(username, password_hash, account_type, mobile, status) VALUES
('test1', '123456', 'consumer', '13000000001', 'active'),
('test2', '123456', 'vendor', '13000000002', 'active');

INSERT INTO t_user_role(user_id, role_id)
SELECT u.id, r.id FROM t_user u JOIN t_role r ON r.role_code = 'consumer' WHERE u.username = 'test1';

INSERT INTO t_user_role(user_id, role_id)
SELECT u.id, r.id FROM t_user u JOIN t_role r ON r.role_code = 'vendor' WHERE u.username = 'test2';

INSERT INTO t_vendor(user_id, vendor_name, story, status)
SELECT id, 'test2 的示例摊位', '用于商家端前端开发的测试摊主账号。', 'approved'
FROM t_user WHERE username = 'test2';

INSERT INTO t_admin(username, password_hash, role_code, status) VALUES
('test3', '123456', 'admin', 'active');
